### ISSUE TITLE
How can I define custom url rather than your template? 

### ISSUE THREAD

**Issue by devbipu** [Erbelion/vite-plugin-laravel-purgecss#3]
Hi, 
I'm working on Laravel & Vue.js project. I've a Vuejs file in `resources/frontend/`
Now how can I define the URL in the config? I can see your template only compile your define path files. How can I purge custom dir files?

**Comment by erbelion** [comment]
@devbipu use paths option instead of templates option, like:
```
import purge from '@erbelion/vite-plugin-laravel-purgecss'

export default {
    plugins: [
        purge({
            paths: ['resources/frontend/**/*.vue']
        })
    ]
}
```
then, all `.vue` files inside `resources/frontend` dir will be purged.

**Comment by devbipu** [comment]
Thank you :)
