### ISSUE TITLE
PostCSS vulnerability - update package

### ISSUE THREAD

**Issue by kamilchojnicki** [Erbelion/vite-plugin-laravel-purgecss#7]
The package uses PostCSS <8.4.31 as a dependency which has a vulnerability. Therefore Snaky.io reports a security concern. The information about it can be found there: 
https://security.snyk.io/vuln/SNYK-JS-POSTCSS-5926692

Please update the dependent packages that use postCSS to one that uses postCSS 8.4.31 or higher. It would also be great if you could update other packages as well.

Thank you

**Comment by erbelion** [comment]
thanks for letting know, i'll update everything in about a week

**Comment by erbelion** [comment]
@kamilchojnicki fixed in 0.2.3

remember to also upgrade postcss in your project after upgrading vite-plugin-laravel-purgecss
